package br.ufma.lsdi.digitalphenotyping.dataprocessor.util;

/**
 * TriggerAlarm1 contains a dataGenerationFrequency flag that manages how often a null data
 * is generated if no data from the module is generated (e.g., within one minute, if no data
 * is generated by the module, a null data is triggered for PhenotypeComposer).
 */
public class TriggerAlarm1 {
    private boolean dataGenerationFrequency;
    private static TriggerAlarm1 instance = null;

    public TriggerAlarm1() {
        dataGenerationFrequency = false;
    }

    public static TriggerAlarm1 getInstance() {
        if (instance == null) {
            instance = new TriggerAlarm1();
        }
        return instance;
    }

    public void set(boolean value) {
        dataGenerationFrequency = value;
    }

    public boolean get(){
        return dataGenerationFrequency;
    }
}